# Generated by Django 3.0.3 on 2020-05-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_testers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roteiro',
            name='cenarios',
            field=models.ManyToManyField(related_name='projetos', to='for_testers.Cenario'),
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='projetos',
            field=models.ManyToManyField(related_name='projetos', to='for_testers.Projeto'),
        ),
    ]
