# Generated by Django 3.0.3 on 2020-05-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_testers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cenario',
            name='criticidade',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='status',
        ),
    ]
