# Generated by Django 3.0.3 on 2020-05-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_testers', '0002_auto_20200504_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenario',
            name='criticidade',
            field=models.CharField(choices=[('A', 'Alta'), ('B', 'Baixa'), ('M', 'Média'), ('AL', 'Altíssima'), ('BX', 'Baixíssima')], default=0, max_length=2, verbose_name='Criticidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('ED', 'Em Desenvolvimento'), ('EH', 'Em Homologação'), ('F', 'Finalizado'), ('NI', 'Não Iniciado')], default=0, max_length=2, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roteiro',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('ET', 'Em Teste'), ('R', 'Reprovado')], default=0, max_length=2, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
