# Generated by Django 3.0.3 on 2020-05-05 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('for_testers', '0003_auto_20200504_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
