# Generated by Django 3.0.3 on 2020-05-05 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('for_testers', '0004_roteiro_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
